### ISSUE TITLE
problems with the require()

### ISSUE THREAD

**Issue by ghost** [LMestre14/react-native-timed-slideshow#1]
When I use `require()` instead of a **url** in the property **uri** of the object **items**, the app stops and takes me out of expo.

```javascript
const items = [
      {
        uri: require('path'),
        title: 'Michael Malik',
        text: 'Minnesota, USA',
      },
      {
        uri: require('path'),
        title: 'Victor Fallon',
        text: 'Val di Sole, Italy',
        duration: 3000,
      },
      {
        uri: require('path'),
        title: 'Mary Gomes',
        text: 'Alps',
        fullWidth: true,
      },
    ];
```

**Comment by ghost** [comment]
I had a similar issue, but with the following error:

`java.lang.Double cannot be cast to java.lang.String`

**Comment by ghost** [comment]
@cr05s19xx exact. That is the error that is giving me. I think it's something a little deep to solve. I do not have enough experience to solve it on my own.

**Comment by LMestre14** [comment]
@cr05s19xx @garciabrito2019 
I've detected the bug and fixed it. Apparently at the end of development for the deploy of the project, I've accidently forgot to verify if the uri was of a local image or of an url image. Sorry for the inconvenience and thanks for using my component
